services:
  - type: web
    name: apexquest-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: static_site
    name: apexquest-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SERVER_URL
        sync: false
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
